MedicalCentre/MedicalCentre.WebUI/Controllers/MedicalCentreController.cs
using MedicalCentre.Repositories;
using MedicalCentre.Repositories.Sql;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedicalCentre.WebUI.Controllers
{
    public class MedicalCentreController : Controller
    {
        private readonly IDoctorRepository _doctorRepository;

        public MedicalCentreController(IDoctorRepository doctorRepository)
        {
            this._doctorRepository = doctorRepository;
        }

        //
        // GET: /MedicalCentre/
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Doctors = _doctorRepository.SelectAllDoctors();
            return View();
        }

        public ActionResult Phone()
        {
            return View();
        }

        public ActionResult Workday()
        {
            return View();
        }

        public ActionResult Appointments()
        {
            return View();
        }

    }
}

MedicalCentre/MedicalCentre.WebUI/Views/MedicalCentre/Appointments.cshtml
@{
    ViewBag.Title = "Appointments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="listdl">
    <form>
        <fieldset>
            <legend>Записатись на прийом</legend>
            <table>
                <tr>
                    <td><label>Прізвище</label></td>
                    <td><input type="text" size="30" /></td>
                </tr>
                <tr>
                    <td><label>Ім'я</label></td>
                    <td><input type="text" size="30" /></td>
                </tr>
                <tr>
                    <td><label>Телефон</label></td>
                    <td><input type="text" size="30" /></td>
                </tr>
                <tr>
                    <td><label>Дата прийому</label></td>
                    <td><input type="datetime-local" size="30" /></td>
                </tr>
                <tr>
                    <td><label>Спеціаліст</label></td>
                    <td>
                        <select>
                            <option selected="selected">---</option>
                            <option>Терапевт</option>
                            <option>Ендокринолог</option>
                            <option>Травматолог</option>
                            <option>Пульмонолог</option>
                            <option>Гінеколог</option>
                            <option>Уролог</option>
                            <option>Імунолог</option>
                            <option>Дерматолог</option>
                            <option>Гастроентеролог</option>
                            <option>Офтальмолог</option>
                            <option>Невропатолог</option>
                            <option>Кардіолог</option>
                            <option>Отоларинголог (ЛОР)</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label>Скарги</label></td>
                    <td><textarea cols="31" rows="4" size="30"></textarea></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" value="Записатись" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>

MedicalCentre/MedicalCentre.WebUI/Views/MedicalCentre/Index.cshtml
@using MedicalCentre.Entities;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<DoctorEntity> doctor = ViewBag.Doctors;
}

<div class="listdl">
    <dl>
        @foreach (var doc in doctor)
        {
            <dt>@doc.Name</dt>
            <dd>@doc.Description</dd>
        }
    </dl>
</div>

MedicalCentre/MedicalCentre.WebUI/Views/MedicalCentre/Phone.cshtml
@{
    ViewBag.Title = "Phone";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="listdl">
    <table border="1">
        <caption>Телефонний довідник</caption>
        <tr>
            <th>№</th>
            <th>Назва</th>
            <th>Телефон</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Головний лікар</td>
            <td>11-22-33</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Реєстратура</td>
            <td>44-55-66</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Довідка</td>
            <td>77-88-99</td>
        </tr>
    </table>
</div>

MedicalCentre/MedicalCentre.WebUI/Views/MedicalCentre/Workday.cshtml
@{
    ViewBag.Title = "Workday";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="listdl">
    <table border="1">
        <caption>Графік прийому лікарів</caption>
        <tr>
            <th>№</th>
            <th>Спеціаліст</th>
            <th>Години прийому</th>
            <th>Дні прийому</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Терапевт</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Ендокринолог</td>
            <td>8:00-17:00</td>
            <td>Понеділок,Середа</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Травматолог</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Пульмонолог</td>
            <td>8:00-17:00</td>
            <td>Середа</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Гінеколог</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Уролог</td>
            <td>8:00-17:00</td>
            <td>Червер</td>
        </tr>
        <tr>
            <td>7</td>
            <td>Імунолог</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
        <tr>
            <td>8</td>
            <td>Дерматолог</td>
            <td>8:00-17:00</td>
            <td>Середа,Четвер</td>
        </tr>
        <tr>
            <td>9</td>
            <td>Гастроентеролог</td>
            <td>8:00-17:00</td>
            <td>Вівторок</td>
        </tr>
        <tr>
            <td>10</td>
            <td>Офтальмолог</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
        <tr>
            <td>11</td>
            <td>Невропатолог</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
        <tr>
            <td>12</td>
            <td>Кардіолог</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
        <tr>
            <td>13</td>
            <td>Отоларинголог (ЛОР)</td>
            <td>8:00-17:00</td>
            <td>Щоденно</td>
        </tr>
    </table>
</div>

MedicalCentre/MedicalCentre.WebUI/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Медичний центр "Швидка допомога"</title>
    @*<link href="~/Images/littleambulance.ico" rel="icon" type="image/x-icon" />*@
    <link href="@Url.Content("~/Images/littleambulance.ico")" rel="stylesheet" type="image/x-icon" />
    @*<link href="~/Styles/StylesIndex.css" rel="stylesheet" type="text/css" />*@
    <link href="@Url.Content("~/Styles/StylesIndex.css")" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/libs/jquery/jquery-2.1.4.js"></script>
</head>
<body>
    <header>
        <h1>Медичний центр "Швидка допомога"</h1>
        <center>
            <div id="menu">
                @Html.ActionLink("Головна", "Index", "MedicalCentre")
                @Html.ActionLink("Графік прийому", "Workday", "MedicalCentre")
                @Html.ActionLink("Запис на прийом", "Appointments", "MedicalCentre")
                @Html.ActionLink("Контакти", "Phone", "MedicalCentre")
            </div>
        </center>
    </header>
    <div>
        @RenderBody()
    </div>
    <div class="space">
        &nbsp;
    </div>
    <div class="car">
        <img src="~/Images/ambulance.png" />
    </div>
    <footer>
        <h6>2015 © Медичний центр “Швидка допомога” м.Рівне</h6>
    </footer>
    <script src="~/Scripts/pages/tasks-page.js"></script>
</body>
</html>